name: PHP Composer + PHPUnit

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    # Limit the running time
    timeout-minutes: 10
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version: ['5.6', '7.0', '7.3', '7.4']

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install PHP ${{ matrix.php-version }} Test on ${{ matrix.operating-system }}"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install no-dev dependencies
      run: composer update --no-dev --prefer-dist --no-progress

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress

    - name: "PHPUnit tests"
      run: "vendor/bin/phpunit"
      # does it work with iconv //TRANSLIT  ?

#    - name: PHPUnit (php-actions)
#      uses: php-actions/phpunit@v5
#      with:
#        # PHP included in ubunut-latest does not support iconv //TRANSLIT flag as iconv implementation is unknown
#        # therefore PHPUnit group iconvtranslit is excluded
#        configuration: phpunit-github-actions.xml

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    # PHPStan works for PHP/7.1+ so it can't even be in composer.json
    - name: "PHPStan"
      if: ${{ matrix.php-version >= '7.1' }}
      run: |
        composer require --dev phpstan/phpstan:^0.12
        vendor/bin/phpstan analyse --no-interaction --no-progress .
