---
name: PHP Composer + PHPUnit + PHPStan

# Obsoleted by polish-the-code.yml workflow, TODO: Remove this workflow in the next minor version. (Also the badge from README.md)

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

permissions:
  contents: read

jobs:
  # Note: https://docs.github.com/en/actions/using-workflows/reusing-workflows The strategy property is not supported in any job that calls a reusable workflow.
  call-workflow:
    uses: WorkOfStan/MyCMS/.github/workflows/php-composer-dependencies-reusable.yml@v0.5.0
    with:
      # JSON
      # "7.2", "7.3", ... Different errors caught by PHPStan 1.x than PHPStan 2.x which is preferred
      php-version: '["7.4"]'
