name: PHP Composer

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: michaelw90/PHP-Lint@master

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install no-dev dependencies
      run: composer update --no-dev --prefer-dist --no-progress

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress

    - name: PHPUnit (php-actions)
      uses: php-actions/phpunit@v5
      with:
        # PHP included in ubunut-latest does not support iconv //TRANSLIT flag as iconv implementation is unknown
        # therefore PHPUnit group iconvtranslit is excluded
        configuration: phpunit-github-actions.xml

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
