name: PHP Composer

on: [push, pull_request]

env:
  LANG: "pt_BR.UTF-8"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: pt_BR.UTF-8
      run: |
          sudo locale-gen pt_BR.UTF-8
          sudo update-locale LANG=pt_BR.UTF-8
    - name: date
      run: |
          date

    - uses: actions/checkout@v2

    - uses: michaelw90/PHP-Lint@master

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install no-dev dependencies
      run: composer update --no-dev --prefer-dist --no-progress

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress

    - name: PHPUnit (php-actions)
      uses: php-actions/phpunit@v5
      with:
        configuration: phpunit.xml

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
